services:
  - type: cron
    name: programa-tap
    schedule: "0 */2 * * *" # Roda de hora em hora, ajuste como quiser
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y wget gnupg unzip curl && \
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
      apt-get update && \
      apt-get install -y google-chrome-stable && \
      pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
